### ISSUE TITLE
•	Create .github folder for workflow automation

### ISSUE THREAD

**Issue by iamAntimPal** [iamAntimPal/ExcelMasteryHub#4]
### 📂 **Milestone: Create `.github` Folder for Workflow Automation**  

📌 **Objective:** Set up the `.github` directory to automate repository management using **GitHub Actions**, **Issue Templates**, **Pull Request Templates**, and **Community Guidelines**. This ensures a smooth contribution process and enhances project efficiency.  

---

### **🛠️ Tasks & Deliverables**  

1️⃣ **Set Up GitHub Actions for Automation**  
   - Create a **workflow** inside `.github/workflows/` to automate tasks like:  
     ✅ Running tests (if applicable)  
     ✅ Checking Markdown formatting  
     ✅ Automatically greeting contributors  
     ✅ Assigning labels to issues/pull requests  
   - Example workflow YAML file (`greet-new-contributors.yml`):  
     ```yaml
     name: Greet New Contributors
     on: [pull_request_target]
     jobs:
       greeting:
         runs-on: ubuntu-latest
         steps:
           - name: Greet Contributor
             uses: actions/first-interaction@v1
             with:
               repo-token: ${{ secrets.GITHUB_TOKEN }}
               issue-message: "👋 Welcome! Thanks for contributing to ExcelMasteryHub!"
               pr-message: "🎉 Thank you for your pull request! A maintainer will review it soon."
     ```

2️⃣ **Create Issue Templates (`.github/ISSUE_TEMPLATE/`)**  
   - Helps **standardize issue reporting** for **bug reports, feature requests, and documentation improvements**.  
   - Example files:  
     - `bug_report.md` (for reporting issues)  
     - `feature_request.md` (for suggesting new features)  
     - `documentation_update.md` (for suggesting changes to docs)  

3️⃣ **Set Up a Pull Request Template (`.github/PULL_REQUEST_TEMPLATE.md`)**  
   - Ensures every PR follows a **structured format** (description, issue reference, checklist).  
   - Example PR template snippet:  
     ```md
     ## Description
     Please include a summary of the changes introduced in this pull request.

     ## Related Issue
     Fixes # (issue number)

     ## Checklist
     - [ ] My code follows the project guidelines.
     - [ ] I have added necessary documentation updates.
     ```

4️⃣ **Add `CODEOWNERS` File**  
   - Specifies **who should review pull requests** for specific files or directories.  
   - Example (`.github/CODEOWNERS`):  
     ```
     # Assigns all changes in "lessons/" to @iamAntimPal  
     lessons/ @iamAntimPal  

     # Assigns all PRs to a specific team  
     * @ExcelMasteryHub/contributors  
     ```

5️⃣ **Create `FUNDING.yml` (Optional: Enable Sponsorships)**  
   - Allows users to support the project via **GitHub Sponsors, Patreon, PayPal**.  
   - Example (`.github/FUNDING.yml`):  
     ```yaml
     github: ["iamAntimPal"]
     patreon: "your-patreon-username"
     ```

6️⃣ **Set Up Community Profile Files**  
   - `.github/CODE_OF_CONDUCT.md` → Defines community behavior guidelines.  
   - `.github/CONTRIBUTING.md` → Guides contributors on how to **report issues, submit PRs, and follow project guidelines**.  

---

### **🎯 Expected Outcome:**  
✅ Automated workflows for **greeting contributors, issue management, and PR reviews**.  
✅ Standardized issue and pull request submission process.  
✅ Defined repository maintenance and contribution guidelines.
